### PR TITLE
rerun failed builds instead of using their cached result

### LINKED ISSUE #45: Consider not caching failed builds
I think that it makes more sense not to cache build failures, most of the time those would be transient errors that should be retried next time someone asks for that build.

In that case we might want to keep the build directory (in a `failed` subdirectory?) for debugging purposes.

### PR DESCRIPTION
**Pull request by dtheodor**
Re-run "ready" jobs whose exit status is not 0. Re-running such a job means removing the existing ready folder and then proceeding as usual, i.e. creating a new pending folder etc.

Closes #45

### CODE REVIEW

File: cmd/mistryd/end_to_end_test.go [hunk 1]
```diff
@@ -176,28 +176,57 @@ func TestResultCache(t *testing.T) {
 
 func TestResultCacheExitCode(t *testing.T) {
```
Comment (agis) [inline cmd/mistryd/end_to_end_test.go]: Does this test case makes sense at all after this change?

File: cmd/mistryd/end_to_end_test.go [hunk 2]
```diff
@@ -176,28 +176,57 @@ func TestResultCache(t *testing.T) {
...
+	if err == nil {
+		t.Fatal("expected error")
+	}
+
+	br, err := parseClientJSON(cmdout)
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	assertNotEq(br.ExitCode, 0, t)
```
Comment (agis) [inline cmd/mistryd/end_to_end_test.go]: Why the exit code is 0 here? Shouldn't it be 33?

Comment (dtheodor) [reply cmd/mistryd/end_to_end_test.go]: we're testing whether the result was cached. a result is now only cached with an exit code of 0. so the test case now needs an exit code of 0

Comment (dtheodor) [reply cmd/mistryd/end_to_end_test.go]: i see we have another test for that actually, so I'm going to remove this one

**Comment by agis** [comment]
LGTM 👏

**Comment by agis** [comment]
Oh, please add an entry in the changelog (under `Changed`). As long as the user is concerned, we a build that errors is not going to be cached.
