### PR TITLE
Build result missing fix

### LINKED ISSUE #75: Build results are getting deleted when docker image build fails
Probably this can be resolved if we copy the pending builds to the ready path every time, no matter the type of failure.

### PR DESCRIPTION
**Pull request by apostergiou**
- [x] Introduce constructor for the BuildInfo
This constructor allows us to set the default ExitCode to 1 (overriding
the go's default 0).
- [x] Properly persist job results in case of failure
With this change, we copy the pending jobs directories to the ready path
whether they have failed or not. This makes sure we keep some
information (build_info.json and out.log files) about the failed jobs.
- [x] Refactor pending hanging jobs removal 
With this change we will handle hanging pending jobs by depending on
setted errors. This enables us to simplify the cleanup flow and drop the
`shouldCleanup` flag. As a side effect in order to be compatible with the current behavior we
take extra care of the LatestBuildPath which should point to the last
successful build.
- [x] Fix bug with overwriting build_info file
The new JSON that is going to overwrite the existing file may be
shorter in length. Thus, leaving some characters behind from the
previous write and making the JSON invalid.
We also remove the file descriptor since it not needed anywhere.

Fixes #75.

### CODE REVIEW

**Comment by apostergiou** [comment]
It makes sense to populate the `BuildInfo` `Err` field in case of errors. But, to do this we would need to refactor the worker. I think we should track it in a separate issue.

@agis @dtheodor feedback is welcome.

File: pkg/types/build_info.go [hunk 1]
```diff
@@ -38,6 +38,17 @@ type ErrImageBuild struct {
 	Err   error
 }
 
+func NewBuildInfo(params Params, path string, transportMethod TransportMethod, startedAt time.Time) *BuildInfo {
+	bi := new(BuildInfo)
+	bi.Params = params
+	bi.Path = path
+	bi.TransportMethod = transportMethod
+	bi.StartedAt = startedAt
+	bi.ExitCode = 1
```
Comment (dtheodor) [inline pkg/types/build_info.go]: I think we should use a special exit code value here to indicate the error condition that the container has not run and this exit code has not been returned by the container. So setting it to `1` doesn't allow us to determine whether this came from the container, or if this is a failure to even start the container

We already do this here
https://github.com/skroutz/mistry/blob/b02896475ff89e0e87f3798a0a477ce5325e7bd2/cmd/mistryd/worker.go#L282-L287

So I'm suggesting to initialize with `bi.ExitCode = -999`, and move the -999 value into a const

File: pkg/types/build_info.go [hunk 2]
```diff
@@ -38,6 +38,17 @@ type ErrImageBuild struct {
 	Err   error
 }
 
+func NewBuildInfo(params Params, path string, transportMethod TransportMethod, startedAt time.Time) *BuildInfo {
```
Comment (agis) [inline pkg/types/build_info.go]: This shouldn't accept any parameters - the user should (if they want to) set individual fields after getting the result of `NewBuildInfo`.

It should just return a buildinfo with `ExitCode` and `StartedAt` initialized.

File: pkg/types/build_info.go (hunk 1 above)
Comment (apostergiou) [reply pkg/types/build_info.go]: Sounds good.

File: pkg/types/build_info.go (hunk 2 above)
Comment (apostergiou) [reply pkg/types/build_info.go]: done

File: cmd/mistryd/job.go [hunk 3]
```diff
@@ -321,10 +321,9 @@ func (j *Job) CloneSrcPath(log *log.Logger) string {
 	return cloneSrc
 }
 
-// BootstrapBuildDir creates all required build directories. Returns true if directories have
-// been partially or fully created and cleanup is required
-func (j *Job) BootstrapBuildDir(fs filesystem.FileSystem, log *log.Logger) (bool, error) {
-	shouldCleanup := false
+// BootstrapBuildDir creates all required build directories. Cleanups the
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/job.go]: fixed

File: cmd/mistryd/worker.go [hunk 4]
```diff
@@ -98,10 +97,38 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
 	}
 
 	log.Printf("Creating new build directory...")
-	cleanupPending, err := j.BootstrapBuildDir(s.cfg.FileSystem, log)
+	err = j.BootstrapBuildDir(s.cfg.FileSystem, log)
+	if err != nil {
+		err = workErr("could not bootstrap build dir", err)
+	}
 
 	defer func() {
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/worker.go]: added

File: cmd/mistryd/worker.go [hunk 5]
```diff
@@ -143,28 +170,12 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
...
-			}
-		}
-	}()
 	biJSON, err := json.Marshal(buildInfo)
 	if err != nil {
 		err = workErr("could not serialize build info", err)
 		return
 	}
-	_, err = infoFile.Write(biJSON)
+	err = ioutil.WriteFile(j.BuildInfoFilePath, biJSON, 0666)
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/worker.go]: There are constants for the file more https://golang.org/pkg/os/#FileMode. So, I think no change is needed.

File: cmd/mistryd/worker.go [hunk 6]
```diff
@@ -188,60 +199,32 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
...
-		err = workErr("could not set the offset for the build_info file", err)
-		return
-	}
 	biJSON, err = json.Marshal(buildInfo)
 	if err != nil {
 		err = workErr("could not serialize build info", err)
 		return
 	}
-	_, err = infoFile.Write(biJSON)
+	err = ioutil.WriteFile(j.BuildInfoFilePath, biJSON, 0666)
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/worker.go]: same as before

File: cmd/mistryd/worker.go [hunk 7]
```diff
@@ -98,10 +97,38 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
...
+			errstr := "could not move pending path"
+			if err == nil {
+				err = fmt.Errorf("%s; %s", errstr, rerr)
+			} else {
+				err = fmt.Errorf("%s; %s | %s", errstr, rerr, err)
+			}
+		}
+
+		if err == nil {
+			// LatestBuildPath always points to the last successful build.
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/worker.go]: reworded and moved the comment

File: cmd/mistryd/worker.go [hunk 8]
```diff
@@ -98,10 +97,38 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
...
+					err = workErr("could not remove latest build link", err)
+					return
+				}
+			}
+			err = os.Symlink(j.ReadyBuildPath, j.LatestBuildPath)
+			if err != nil {
+				err = workErr("could not create latest build link", err)
+				return
+			}
+		} else {
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/worker.go]: added

File: cmd/mistryd/worker.go [hunk 9]
```diff
@@ -98,10 +97,38 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
...
+		if rerr != nil {
+			errstr := "could not move pending path"
+			if err == nil {
+				err = fmt.Errorf("%s; %s", errstr, rerr)
+			} else {
+				err = fmt.Errorf("%s; %s | %s", errstr, rerr, err)
+			}
+		}
+
+		if err == nil {
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/worker.go]: added

**Comment by agis** [comment]
> It makes sense to populate the BuildInfo Err field in case of errors. But, to do this we would need to refactor the worker. I think we should track it in a separate issue.

Yeah it makes sense to do so in another patch.

File: cmd/mistryd/worker.go [hunk 10]
```diff
@@ -98,10 +97,40 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
...
+				err = fmt.Errorf("%s; %s", errstr, rerr)
+			} else {
+				err = fmt.Errorf("%s; %s | %s", errstr, rerr, err)
+			}
+		}
+
+		// When there are no errors the LatestBuildPath can be updated
+		// to point to the last build. Otherwise it remains unchanged.
+		if err == nil {
+			_, err = os.Lstat(j.LatestBuildPath)
```
Comment (dtheodor) [inline cmd/mistryd/worker.go]: What happens if the `err` from `os.Lstat` is not nil?

Comment (agis) [reply cmd/mistryd/worker.go]: Nice catch.

File: cmd/mistryd/end_to_end_test.go [hunk 11]
```diff
@@ -223,6 +223,32 @@ func TestImageBuildFailure(t *testing.T) {
...
+	bi := types.NewBuildInfo()
+	biBlob, err := ioutil.ReadFile(buildInfoPath)
+	if err != nil {
+		t.Fatalf("%s", err)
+	}
+	err = json.Unmarshal(biBlob, bi)
+	if err != nil {
+		t.Fatalf("%s", err)
+	}
+	assertEq(bi.ExitCode, -999, t)
```
Comment (dtheodor) [inline cmd/mistryd/end_to_end_test.go]: I'm replacing all references to `-999` with `types.ContainerFailureExitCode`

File: cmd/mistryd/worker.go [hunk 12]
```diff
@@ -98,10 +97,40 @@ func (s *Server) Work(ctx context.Context, j *Job) (buildInfo *types.BuildInfo,
...
+					return
+				}
+			}
+			err = os.Symlink(j.ReadyBuildPath, j.LatestBuildPath)
+			if err != nil {
+				err = workErr("could not create latest build link", err)
+			}
+			// An error at this point indicates that there is a hanging pending path.
+		} else {
 			derr := s.cfg.FileSystem.Remove(j.PendingBuildPath)
```
Comment (dtheodor) [inline cmd/mistryd/worker.go]: We don't need to `Remove(j.PendingBuildPath)` any more. We  always `os.Rename(j.PendingBuildPath, j.ReadyBuildPath)`. If that move fails, this means that we either have a bug or there is some system/permission error and manual intervention is needed by an admin to solve the issue. So I think we should never do  `Remove(j.PendingBuildPath)` here any more

Comment (agis) [reply cmd/mistryd/worker.go]: True.
