### PR TITLE
Fix streaming

### LINKED ISSUE #71: web view doesn't stream logs properly

### PR DESCRIPTION
**Pull request by apostergiou**
**Fix a bug with web view log streaming**
The bug was based in a racy condition that could be triggered when a
tailer had been terminated for a job ID just after a new job with the
same ID has started streaming.

To solve this we refactor the concurrency model of the tailers by
removing the sync map and depending only on new and closing clients
signals sent to the broker.

Fixes #71

Some other improvements:

- Fix a bug with clients number being negative
- broker: Close client channels when done

### CODE REVIEW

File: pkg/broker/broker.go [hunk 1]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
 		case sb := <-br.NewClients:
 			br.clients[sb] = true
 			cc, ok := br.clientsCount.Load(sb.ID)
-			if ok {
+			if ok && cc.(int) > 0 {
```
Comment (agis) [inline pkg/broker/broker.go]: We should check here that the conversion works successfully. If we don't do so, this may panic, which is definitely unwanted.

File: pkg/broker/broker.go [hunk 2]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
 				br.clientsCount.Store(sb.ID, cc.(int)+1)
 			} else {
 				br.clientsCount.Store(sb.ID, 1)
+				br.CloseClientC[sb.ID] = make(chan struct{})
+				tl, err := tailer.New(sb.Extra)
```
Comment (agis) [inline pkg/broker/broker.go]: Error check?

File: pkg/broker/broker.go [hunk 3]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
+				go func() {
+					br.Log.Printf("[tailer] Starting for %s", sb.ID)
+
+					scanner := bufio.NewScanner(tl)
+					for scanner.Scan() {
+						br.Notifier <- &Event{Msg: []byte(scanner.Text()), ID: sb.ID}
+					}
+				}()
+				go func() {
+					<-br.CloseClientC[sb.ID]
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply pkg/broker/broker.go]: Sure it would, that way we would notify the Tailer explicitly when it needs to terminate. 

Regardless of how we terminate the Tailer though, either explicitly with a channel message or implicitly with closing the file in question, I think the complexity would remain the same as we need the goroutine in order not to block while listening to the `br.CloseClientC` channel.

File: pkg/broker/broker.go [hunk 4]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
+					br.Log.Printf("[tailer] Exiting for: %s", sb.ID)
+					err = tl.Close()
+					if err != nil {
+						br.Log.Print(err)
+					}
+				}()
 			}
 			br.Log.Printf("[broker] Client added. %d registered clients", len(br.clients))
 		case sb := <-br.ClosingClients:
```
Comment (agis) [inline pkg/broker/broker.go]: Rename this variable to "client".

File: pkg/broker/broker.go [hunk 5]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
+			close(sb.EventC)
 			delete(br.clients, sb)
 			cc, ok := br.clientsCount.Load(sb.ID)
-			if ok {
+			if ok && cc.(int) > 0 {
```
Comment (agis) [inline pkg/broker/broker.go]: Check if conversion succeeds, otherwise this may panic.

File: pkg/broker/broker.go [hunk 6]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
 				br.clientsCount.Store(sb.ID, cc.(int)-1)
 			} else {
 				br.clientsCount.Store(sb.ID, 0)
 			}
 			br.Log.Printf("[broker] Removed client. %d registered clients", len(br.clients))
```
Comment (agis) [inline pkg/broker/broker.go]: Before we merge this and *after* making sure the logic works as expected, we should remove all these debug logs ("added client, removed client, closed tailer, new tailer etc.")

We should only log errors.

File: pkg/broker/broker.go [hunk 7]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
 			cc, ok = br.clientsCount.Load(sb.ID)
-			if ok && cc.(int) == 0 {
+			if ok && cc.(int) <= 0 {
```
Comment (agis) [inline pkg/broker/broker.go]: Check error from conversion or this may panic.

Also, is the `<= 0` check needed?

File: pkg/broker/broker.go [hunk 8]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
+					br.Log.Printf("[tailer] Exiting for: %s", sb.ID)
+					err = tl.Close()
+					if err != nil {
+						br.Log.Print(err)
+					}
+				}()
 			}
 			br.Log.Printf("[broker] Client added. %d registered clients", len(br.clients))
 		case sb := <-br.ClosingClients:
+			close(sb.EventC)
```
Comment (agis) [inline pkg/broker/broker.go]: Rename "EventC" to something better like "Messages" or "Data" or "Logs"

File: pkg/broker/broker.go [hunk 9]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
+			if ok && cc.(int) > 0 {
 				br.clientsCount.Store(sb.ID, cc.(int)+1)
 			} else {
 				br.clientsCount.Store(sb.ID, 1)
+				br.CloseClientC[sb.ID] = make(chan struct{})
+				tl, err := tailer.New(sb.Extra)
+				go func() {
+					br.Log.Printf("[tailer] Starting for %s", sb.ID)
+
+					scanner := bufio.NewScanner(tl)
```
Comment (agis) [inline pkg/broker/broker.go]: Since this variable is only used in the subsequent line, it could be renamed to the shorter "s".

File: pkg/broker/broker.go [hunk 10]
```diff
@@ -42,6 +45,9 @@ type Client struct {
 	// Each connection has an id that corresponds to the Event ID it is
 	// interested in receiving messages about.
 	ID string
+
+	// Extra contains any extra misc information about the connection.
```
Comment (agis) [inline pkg/broker/broker.go]: Like what? Can we provide an example?

Comment (apostergiou) [reply pkg/broker/broker.go]: `Extra` may include information such as the path of a file to be read. Added an example.

File: cmd/mistryd/server.go [hunk 11]
```diff
@@ -47,7 +42,6 @@ type Server struct {
 	// Queue used to track all open tailers by their id. Every tailer id
 	// matches a job id.
 	// The stored map type is [string]bool.
-	tq *sync.Map
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/server.go]: true, done

File: cmd/mistryd/server.go [hunk 12]
```diff
@@ -379,11 +311,13 @@ func (s *Server) HandleServerPush(w http.ResponseWriter, r *http.Request) {
...
 
-	client := &broker.Client{ID: id, EventC: make(chan []byte)}
+	jPath := filepath.Join(s.cfg.BuildPath, project, state, id)
+	buildLogPath := filepath.Join(jPath, BuildLogFname)
+	client := &broker.Client{ID: id, EventC: make(chan []byte), Extra: buildLogPath}
 	s.br.NewClients <- client
 
 	defer func() {
-		s.br.ClosingClients <- client
+		s.Log.Printf("Finished server push event at %s", r.URL.Path)
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply cmd/mistryd/server.go]: Yep, I used it to get some more information while debugging the handle closing but it's not needed in production.

File: pkg/broker/broker.go [hunk 13]
```diff
@@ -76,23 +82,42 @@ func (br *Broker) ListenForClients() {
...
 			br.Log.Printf("[broker] Client added. %d registered clients", len(br.clients))
 		case sb := <-br.ClosingClients:
+			close(sb.EventC)
 			delete(br.clients, sb)
 			cc, ok := br.clientsCount.Load(sb.ID)
-			if ok {
+			if ok && cc.(int) > 0 {
 				br.clientsCount.Store(sb.ID, cc.(int)-1)
 			} else {
 				br.clientsCount.Store(sb.ID, 0)
```
[the remark this answers is not in the document]
Comment (apostergiou) [reply pkg/broker/broker.go]: Good catch, fixed.

File: pkg/broker/broker.go (hunk 1 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: Thanks for clarifying, fixed.

File: pkg/broker/broker.go (hunk 2 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: Added

File: pkg/broker/broker.go (hunk 4 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: done, it was about time we do this :smile:

File: pkg/broker/broker.go (hunk 5 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: fixed

File: pkg/broker/broker.go (hunk 6 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: sure

File: pkg/broker/broker.go (hunk 7 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: Added check for the type assertion. The `<= 0` is not needed indeed, it was a somewhat ugly patch for a past bug.

File: pkg/broker/broker.go (hunk 8 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: done

File: pkg/broker/broker.go (hunk 9 above)
Comment (apostergiou) [reply pkg/broker/broker.go]: fixed
